### ISSUE TITLE
Violin plots appear like they are not violins

### ISSUE THREAD

**Issue by envest** [greenelab/RNAseq_titration_results#144]
Exploration: can we adjust violin plot line thickness such that it does not obscure the shape of the distributions

**Comment by envest** [comment]
@jaclyn-taroni I made the outlines less thick to highlight the shapes of each violin... Thoughts? I can propagate this change to other plots. 

![BRCA_subtype_train_3_models_kappa](https://user-images.githubusercontent.com/10382980/207705983-b0cf2341-8ad7-4fd5-b78b-ec9af8147c35.png)

**Comment by envest** [comment]
Compared to the original

![BRCA_subtype_train_3_models_kappa original](https://user-images.githubusercontent.com/10382980/207708072-792e9edf-2bb5-4ff5-b813-78149b8fc494.png)

**Comment by jaclyn-taroni** [comment]
That does make them look more like violin plots in my opinion. Do they look enough like violin plots in every case to read as violin plots? I'm not sure.

**Comment by envest** [comment]
Summary of slack discussion with @jaclyn-taroni 

- Most important things to communicate: median values and horizontal shape (flat good, slanted less good)
- Variability between repeats: violin shape uninformative, try a confidence interval around median
- Jackie referenced [this SO conversation](https://stackoverflow.com/questions/68123031/understanding-the-numbers-in-ggplot2-doc-about-boxplot)

The notches in a box plot correspond to a ROUGH 95% confidence interval around median: `median +/- 1.58*IQR/sqrt(n)`

where `IQR` is inter-quartile range, and `n` is the number of observations (ideally >= 10, which we have)

**Comment by envest** [comment]
Here is another draft, showing error bars for 95% CI around median. It also has reduced weight of the panel grid lines.

![BRCA_subtype_train_3_models_kappa](https://user-images.githubusercontent.com/10382980/207912259-e0f04708-8047-4c87-8f98-25e856d56b07.png)
