### ISSUE TITLE
Diagnose and fix problems experienced with R 4.0.3

### ISSUE THREAD

**Issue by envest** [greenelab/RNAseq_titration_results#41]
When updating code to run in 2021, we experienced different (worse) prediction behavior than expected based on previous results.

Changing the R version from 4.0.3 back to 3.6.3 worked to resolve this problem. R 3.6.3 was the February 2020 release immediately before R 4.0.0 later that year. In the long term, understanding what went differently under 4.0.3 vs. 3.6.3 will be important for future code updates that may rely on R 4+. One potentially related issue is from the `greenelab/TDM` package. The problem with our results may be in part due to the experiences documented here: https://github.com/greenelab/TDM/issues/5.

Potential ways to resolve:
- Running the code in two parallel environments and comparing results at each step
- Try with an updated version of TDM when there is an update

**Comment by envest** [comment]
Update to latest R version and then rebuild multi-architecture docker image (amd64 + arm64)

**Comment by jashapiro** [comment]
> Update to latest R version and then rebuild multi-architecture docker image (amd64 + arm64)
New chip, who dis?

**Comment by envest** [comment]
Resolved! [greenelab/TDM#7](https://github.com/greenelab/TDM/issues/7)
