### ISSUE TITLE
Update differential expression scripts for new files name structure

### ISSUE THREAD

**Issue by envest** [greenelab/RNAseq_titration_results#68]
Scripts including

1. 1A-detect_differentially_expressed_genes.R
2. 2A-plot_DE_results.R
3. 3A-small_n_differential_expression.R

need to be updated to accommodate our new file name scheme (`cancertype_predictor_rest_of_filename`).

**Comment by envest** [comment]
@jaclyn-taroni @cgreene , I want to have science discussion here before going down code review trail...

The original purpose of these scripts is to detect differentially expressed genes between subtypes. Theoretically we now have the power to extend this analysis to detect DEGs between mutated/non-mutated samples. Do we want to make this jump? My instinct says no, not right now, we can later, but it's not necessary.

The main change that must happen is updating the file naming scheme to accommodate `predictor` (either subtype or a gene name) that is now part of the input file name. My preference is to simply assert we are focusing on subtype.

Thoughts?

**Comment by jaclyn-taroni** [comment]
> Do we want to make this jump? My instinct says no, not right now, we can later, but it's not necessary.

Agreed!
