### ISSUE TITLE
Visualize expression values before and after normalization

### ISSUE THREAD

**Issue by envest** [greenelab/RNAseq_titration_results#76]
- Look at raw expression values of original data
- Compare RNA-seq and array expression values before and after normalization

**Comment by envest** [comment]
Need to check that TDM for 0% RNA-seq is specified properly

**Comment by envest** [comment]
Before making this a PR, I thought we should discuss here. The main question is: does our visualization satisfy the request of the reviewer?

One reviewer suggested visualizing expression data patterns of matched array and seq samples after normalization. A few months back, we examined this using and scatter plots and hex plots of gene expression values from a downsampled set of genes. I've kept that style here in recent updates. I experimented a little with log scaling the UN RNA-seq values, but thought maybe we want to keep it raw for this application. Some GBM examples are attached.

This may satisfy the reviewer's question by showing how values match up before normalization (UN) vs. how they match up after our various normalization strategies. Thoughts?

[GBM_subtype.UN.hex.pdf](https://github.com/greenelab/RNAseq_titration_results/files/7857569/GBM_subtype.UN.hex.pdf)
[GBM_subtype.LOG.hex.pdf](https://github.com/greenelab/RNAseq_titration_results/files/7857572/GBM_subtype.LOG.hex.pdf)
[GBM_subtype.NPN.hex.pdf](https://github.com/greenelab/RNAseq_titration_results/files/7857577/GBM_subtype.NPN.hex.pdf)
[GBM_subtype.QN_50.hex.pdf](https://github.com/greenelab/RNAseq_titration_results/files/7857579/GBM_subtype.QN_50.hex.pdf)
[GBM_subtype.QN-Z.hex.pdf](https://github.com/greenelab/RNAseq_titration_results/files/7857585/GBM_subtype.QN-Z.hex.pdf)
[GBM_subtype.TDM_50.hex.pdf](https://github.com/greenelab/RNAseq_titration_results/files/7857581/GBM_subtype.TDM_50.hex.pdf)
[GBM_subtype.Z.hex.pdf](https://github.com/greenelab/RNAseq_titration_results/files/7857583/GBM_subtype.Z.hex.pdf)

**Comment by envest** [comment]
Looking back at our meeting notes from 11 Nov 2021, I had written:

> Explain the experimental design again, show the plots of matched sample expression data, and move on

**Comment by jaclyn-taroni** [comment]
Including these plots & restating the experimental design makes sense to me!
